[DEM-1513] add pylint to pipeline
QuTech-Delft/qilib pull request #94
Opened 2020-10-09 09:42 UTC by bogdanvconstantin

2020-10-09 10:00 UTC, QFer submitted a review, later dismissed

2020-10-14 07:07 UTC, oschusler requested changes

2020-10-14 07:07 UTC, oschusler commented on .travis.yml
> +- pylint src || true
Same comment. Should be `qilib`

2020-10-14 09:07 UTC, oschusler approved these changes

2020-10-14 19:23 UTC, oschusler commented
@QFer can you please hit the approve button again?

2020-10-15 07:03 UTC, QFer approved these changes

2020-10-15 07:06 UTC, merged